name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and release
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up golang env
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0-beta1'

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/checkout@v2

      - name: Get dependencies
        run: go get

      - name: Build
        run: make

      - uses: actions/upload-artifact@v2
        with:
          name: fakeps-${{ runner.os }}
          path: fakeps

